import {ConvolutionOrCorrelationMapperOperatorKernel} from "../ConvolutionOrCorrelationMapperOperatorKernel.ts";
export const emptyConvolutionOrCorrelationMapperOperatorKernel =
	ConvolutionOrCorrelationMapperOperatorKernel.createEmpty();
